on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "!.github/workflows/test-suite.yaml"

name: PR Build
permissions:
    contents: read
jobs:
  test-amd64:
    runs-on: runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }},image=ubuntu22-full-x64,hdd=64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: windows/amd64

    - name: Configure Windows container support
      run: |
        docker buildx create --use --platform windows/amd64

    - name: docker --bootstrap
      run: |
        docker buildx inspect --bootstrap

    - name: test build image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        export GOARCH=amd64
        export GOOS=windows
        export IID_FILE=$(mktemp)
        export IID_FILE_FLAG="--iidfile ${IID_FILE}"

        echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart

        make publish-image-runtime-windows
