on:
  push:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "!.github/workflows/test-suite.yaml"
    tags:
    - "v*"

env:
  GITHUB_ACTION_TAG: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}
  
name: Release
permissions:
    contents: write
    id-token: write
jobs:
  release-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Validate Release
      run: |
        make in-docker-validate-release

    - name: Build
      run: |
        make ci

    - name: Package Images
      run: |
        make in-docker-package-images
    
    - name: Scan Images
      continue-on-error: true
      run: |
        make in-docker-scan-images
    - name: Upload Scan Results
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: release-trivy-scan
        path: trivy_scan_report.txt

    - name: Load kernel modules
      run: |
       sudo modprobe br_netfilter overlay
        
    - name: Test
      run: |
        make in-docker-test

    - name: Set environment variables
      run: |
        echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

    - name: Publish Image Runtime - Docker
      uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # v0.65.2
      env:
        GOARCH: amd64
        GOOS: linux
      with:
        image: "rke2-runtime"
        tag: ${{ env.GIT_TAG }}
        make-target: publish-image-runtime

        public-repo: ${{ secrets.DOCKER_USERNAME }}
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PASSWORD }}

        push-to-prime: false

    - name: Publish Image Runtime (Windows) - Docker
      uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # v0.65.2
      env:
        GOARCH: amd64
        GOOS: linux
      with:
        image: "rke2-runtime"
        tag: ${{ env.GIT_TAG }}
        make-target: publish-image-runtime-windows

        public-repo: ${{ secrets.DOCKER_USERNAME }}
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PASSWORD }}

        push-to-prime: false
  
    - name: Package windows images
      run: |
        GITHUB_ACTION_TAG=${{ github.ref_name }} make in-docker-package-windows-images

    - name: Checksum Artifacts
      run: |
        GITHUB_ACTION_TAG=${{ github.ref_name }} make in-docker-checksum

    - name: Upload artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: rke2-artifacts-amd64
        path: |
          dist/artifacts/*.txt
          dist/artifacts/rke2.*
          dist/artifacts/*.exe
        if-no-files-found: error

  release-arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Validate Release
      run: |
       make in-docker-validate-release

    - name: Build
      run: |
        make ci

    - name: Package Images
      run: |
        make in-docker-package-images
    
    - name: Scan Images
      continue-on-error: true
      run: |
        make in-docker-scan-images

    - name: Set environment variables
      run: |
        echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

    - name: Publish Image Runtime - Docker
      uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # v0.65.2
      env:
        GOARCH: arm64
        GOOS: linux
      with:
        image: "rke2-runtime"
        tag: ${{ env.GIT_TAG }}
        make-target: publish-image-runtime

        public-repo: ${{ secrets.DOCKER_USERNAME }}
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PASSWORD }}

        push-to-prime: false

    - name: Checksum
      run: |
        GITHUB_ACTION_TAG=${{ github.ref_name }} make in-docker-checksum

    - name: Upload artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: rke2-artifacts-arm64
        path: |
          dist/artifacts/*.txt
          dist/artifacts/rke2.*
        if-no-files-found: error

  create-draft-release:
    name: "Create draft release"
    needs: [release-amd64, release-arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Download image lists
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
      with:
        pattern: rke2-artifacts-*
        merge-multiple: true
        path: dist/artifacts
    - name: Publish Artifacts
      run: |
        make in-docker-publish-binary
      env:
        GH_TOKEN: ${{ github.token }}

  manifest:
    needs: [release-amd64, release-arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Set environment variables
      run: |
        echo "GIT_TAG=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')" >> "$GITHUB_ENV"

    - name: Manifest - Docker
      uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # v0.65.2
      env:
        GOARCH: amd64
        GOOS: linux
      with:
        image: "rke2-runtime"
        tag: ${{ env.GIT_TAG }}
        make-target: publish-manifest-runtime

        public-repo: ${{ secrets.DOCKER_USERNAME }}
        public-username: ${{ secrets.DOCKER_USERNAME }}
        public-password: ${{ secrets.DOCKER_PASSWORD }}

        push-to-prime: false
